runtime: python39
env: standard
instance_class: F1
handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico
  - url: /static/(.*\.css)
    mime_type: text/css
    static_files: static/\1
    upload: static/(.*\.css)
  - url: /static/(.*\.js)
    mime_type: text/javascript
    static_files: static/\1
    upload: static/(.*\.js)
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  min_instances: 1
  max_instances: 15
