automatic_scaling:
  max_instances: 15
  min_idle_instances: 1
  min_instances: 1

handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /static/(.*\.css)
    mime_type: text/css
    static_files: static/\1
    upload: static/(.*\.css)

  - url: /static/(.*\.js)
    mime_type: text/javascript
    static_files: static/\1
    upload: static/(.*\.js)

instance_class: F4
runtime: python39

